In [788]:
import pandas as pd
import numpy as np
import ast
import json
import requests
from bs4 import BeautifulSoup
from lxml import html
import requests
from numpy import NaN
from collections import Counter

In [3]:
df = pd.read_csv('../../data/01-modified-data/data_cleaning_R.csv')

a = 0
b = 1
c = 2
d = 3
e = 4

for i in range(1096):
    
    df['Driver_Position'][a] = df['Driver_Position_1'][a]
    df['Driver_Position'][b] = df['Driver_Position_2'][b]
    df['Driver_Position'][c] = df['Driver_Position_3'][c]
    df['Driver_Position'][d] = df['Driver_Position_4'][d]
    df['Driver_Position'][e] = df['Driver_Position_5'][e]
    
    df['Driver_Points'][a] = df['Driver_Points_1'][a]
    df['Driver_Points'][b] = df['Driver_Points_2'][b]
    df['Driver_Points'][c] = df['Driver_Points_3'][c]
    df['Driver_Points'][d] = df['Driver_Points_4'][d]
    df['Driver_Points'][e] = df['Driver_Points_5'][e]
    
    df['driverRef'][a] = df['driverRef_1'][a]
    df['driverRef'][b] = df['driverRef_2'][b]
    df['driverRef'][c] = df['driverRef_3'][c]
    df['driverRef'][d] = df['driverRef_4'][d]
    df['driverRef'][e] = df['driverRef_5'][e]
    
    df['constructorRef'][a] = df['constructorRef_1'][a]
    df['constructorRef'][b] = df['constructorRef_2'][b]
    df['constructorRef'][c] = df['constructorRef_3'][c]
    df['constructorRef'][d] = df['constructorRef_4'][d]
    df['constructorRef'][e] = df['constructorRef_5'][e]
    
    df['grid_pos'][a] = df['grid_pos_1'][a]
    df['grid_pos'][b] = df['grid_pos_2'][b]
    df['grid_pos'][c] = df['grid_pos_3'][c]
    df['grid_pos'][d] = df['grid_pos_4'][d]
    df['grid_pos'][e] = df['grid_pos_5'][e]
    
    df['race_status'][a] = df['race_status_1'][a]
    df['race_status'][b] = df['race_status_2'][b]
    df['race_status'][c] = df['race_status_3'][c]
    df['race_status'][d] = df['race_status_4'][d]
    df['race_status'][e] = df['race_status_5'][e]
    
    df['race_time'][a] = df['race_time_1'][a]
    df['race_time'][b] = df['race_time_2'][b]
    df['race_time'][c] = df['race_time_3'][c]
    df['race_time'][d] = df['race_time_4'][d]
    df['race_time'][e] = df['race_time_5'][e]
    
    df['completed_laps'][a] = df['completed_laps_1'][a]
    df['completed_laps'][b] = df['completed_laps_2'][b]
    df['completed_laps'][c] = df['completed_laps_3'][c]
    df['completed_laps'][d] = df['completed_laps_4'][d]
    df['completed_laps'][e] = df['completed_laps_5'][e]
    
    a = a+5
    b = b+5
    c = c+5
    d = d+5
    e = e+5
    
drop = ['Driver_Position_1', 'Driver_Position_2', 'Driver_Position_3', 'Driver_Position_4', 'Driver_Position_5',
             'Driver_Points_1', 'Driver_Points_2', 'Driver_Points_3', 'Driver_Points_4', 'Driver_Points_5',
             'driverRef_1', 'driverRef_2', 'driverRef_3', 'driverRef_4', 'driverRef_5',
             'constructorRef_1', 'constructorRef_2', 'constructorRef_3', 'constructorRef_4', 'constructorRef_5',
             'grid_pos_1', 'grid_pos_2', 'grid_pos_3', 'grid_pos_4', 'grid_pos_5', 
             'completed_laps_1', 'completed_laps_2', 'completed_laps_3', 'completed_laps_4', 'completed_laps_5',
             'race_status_1', 'race_status_2', 'race_status_3', 'race_status_4', 'race_status_5',
             'race_time_1', 'race_time_2', 'race_time_3', 'race_time_4', 'race_time_5']

df.drop(drop, axis = 1, inplace=True)

df.to_csv('../../data/01-modified-data/race_result_cleaned.csv')

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Position'][a] = df['Driver_Position_1'][a]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Position'][b] = df['Driver_Position_2'][b]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Position'][c] = df['Driver_Position_3'][c]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Position'][d] = df['Driver_Position_4'][d]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Position'][e] = df['Driver_Position_5'][e]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Points'][a] = df['Driver_Points_1'][a]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Points'][b] = df['Driver_Points_2'][b]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Points'][c] = df['Driver_Points_3'][c]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Points'][d] = df['Driver_Points_4'][d]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Driver_Points'][e] = df['Driver_Points_5'][e]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['driverRef'][a] = df['driverRef_1'][a]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['driverRef'][b] = df['driverRef_2'][b]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['driverRef'][c] = df['driverRef_3'][c]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['driverRef'][d] = df['driverRef_4'][d]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['driverRef'][e] = df['driverRef_5'][e]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['constructorRef'][a] = df['constructorRef_1'][a]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['constructorRef'][b] = df['constructorRef_2'][b]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['constructorRef'][c] = df['constructorRef_3'][c]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['constructorRef'][d] = df['constructorRef_4'][d]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['constructorRef'][e] = df['constructorRef_5'][e]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['grid_pos'][a] = df['grid_pos_1'][a]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['grid_pos'][b] = df['grid_pos_2'][b]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['grid_pos'][c] = df['grid_pos_3'][c]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['grid_pos'][d] = df['grid_pos_4'][d]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['grid_pos'][e] = df['grid_pos_5'][e]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_status'][a] = df['race_status_1'][a]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_status'][b] = df['race_status_2'][b]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_status'][c] = df['race_status_3'][c]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_status'][d] = df['race_status_4'][d]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_status'][e] = df['race_status_5'][e]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_time'][a] = df['race_time_1'][a]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_time'][b] = df['race_time_2'][b]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_time'][c] = df['race_time_3'][c]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_time'][d] = df['race_time_4'][d]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race_time'][e] = df['race_time_5'][e]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['completed_laps'][a] = df['completed_laps_1'][a]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['completed_laps'][b] = df['completed_laps_2'][b]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['completed_laps'][c] = df['completed_laps_3'][c]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['completed_laps'][d] = df['completed_laps_4'][d]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_2322/965883419.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['completed_laps'][e] = df['completed_laps_5'][e]

In [678]:
ds_df = pd.read_csv('../../data/00-raw-data/driver_standings.csv')
ast.literal_eval(ds_df['DriverStandings'][0])[0]

{'position': '1',
 'positionText': '1',
 'points': '30',
 'wins': '3',
 'Driver': {'driverId': 'farina',
  'url': 'http://en.wikipedia.org/wiki/Nino_Farina',
  'givenName': 'Nino',
  'familyName': 'Farina',
  'dateOfBirth': '1906-10-30',
  'nationality': 'Italian'},
 'Constructors': [{'constructorId': 'alfa',
   'url': 'http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One',
   'name': 'Alfa Romeo',
   'nationality': 'Swiss'}]}

In [679]:
ds_df

,Unnamed: 0,season,round,DriverStandings
0,0,1950,7,"[{'position': '1', 'positionText': '1', 'point..."
1,1,1951,8,"[{'position': '1', 'positionText': '1', 'point..."
2,2,1952,8,"[{'position': '1', 'positionText': '1', 'point..."
3,3,1953,9,"[{'position': '1', 'positionText': '1', 'point..."
4,4,1954,9,"[{'position': '1', 'positionText': '1', 'point..."
...,...,...,...,...
70,70,2017,20,"[{'position': '1', 'positionText': '1', 'point..."
71,71,2018,21,"[{'position': '1', 'positionText': '1', 'point..."
72,72,2019,21,"[{'position': '1', 'positionText': '1', 'point..."
73,73,2020,17,"[{'position': '1', 'positionText': '1', 'point..."
74,74,2021,22,"[{'position': '1', 'positionText': '1', 'point..."

In [680]:
season_list = list(df['season'].unique())

In [681]:
ds_df_1 = pd.DataFrame(columns=['driverRef'] + season_list)

In [682]:
ds_df_1['driverRef'] = driver_df['driverRef']

In [683]:
ds_df_1.fillna(0, inplace=True)

In [684]:
ds_df_1

,driverRef,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,hamilton,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,heidfeld,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,rosberg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,alonso,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,kovalainen,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,tsunoda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
851,mazepin,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
852,mick_schumacher,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
853,zhou,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
854,de_vries,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [685]:
for i in range(len(ds_df)):
    
    for j in range(len(ast.literal_eval(ds_df['DriverStandings'][i]))):
        
        points = ast.literal_eval(ds_df['DriverStandings'][i])[j]['points']
        driver = ast.literal_eval(ds_df['DriverStandings'][i])[j]['Driver']['driverId']
        
        if points == '':
            points = 0
            
        for k in range(len(ds_df_1)):
            
            if driver == ds_df_1['driverRef'][k]:
                ds_df_1[int(ds_df['season'][i])][k] = points

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3830417705.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds_df_1[int(ds_df['season'][i])][k] = points

In [686]:
ds_df_1

,driverRef,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,hamilton,0,0,0,0,0,0,0,0,0,...,189,384,381,380,363,408,413,347,387.5,0
1,heidfeld,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,rosberg,0,0,0,0,0,0,0,0,0,...,171,317,322,385,0,0,0,0,0,0
3,alonso,0,0,0,0,0,0,0,0,0,...,242,161,11,54,17,50,0,0,81,0
4,kovalainen,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,tsunoda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,32,0
851,mazepin,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
852,mick_schumacher,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
853,zhou,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
854,de_vries,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [687]:
race_results_df = pd.read_csv('../../data/00-raw-data/race_results.csv')

In [688]:
race_results_df

,Unnamed: 0,season,round,url,raceName,Circuit,date,Results,time
0,0,1950,1,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,"{'circuitId': 'silverstone', 'url': 'http://en...",1950-05-13,"[{'number': '2', 'position': '1', 'positionTex...",NaN
1,1,1950,2,http://en.wikipedia.org/wiki/1950_Monaco_Grand...,Monaco Grand Prix,"{'circuitId': 'monaco', 'url': 'http://en.wiki...",1950-05-21,"[{'number': '34', 'position': '1', 'positionTe...",NaN
2,2,1950,3,http://en.wikipedia.org/wiki/1950_Indianapolis...,Indianapolis 500,"{'circuitId': 'indianapolis', 'url': 'http://e...",1950-05-30,"[{'number': '1', 'position': '1', 'positionTex...",NaN
3,3,1950,4,http://en.wikipedia.org/wiki/1950_Swiss_Grand_...,Swiss Grand Prix,"{'circuitId': 'bremgarten', 'url': 'http://en....",1950-06-04,"[{'number': '16', 'position': '1', 'positionTe...",NaN
4,4,1950,5,http://en.wikipedia.org/wiki/1950_Belgian_Gran...,Belgian Grand Prix,"{'circuitId': 'spa', 'url': 'http://en.wikiped...",1950-06-18,"[{'number': '10', 'position': '1', 'positionTe...",NaN
...,...,...,...,...,...,...,...,...,...
1091,1091,2022,12,http://en.wikipedia.org/wiki/2022_French_Grand...,French Grand Prix,"{'circuitId': 'ricard', 'url': 'http://en.wiki...",2022-07-24,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z
1092,1092,2022,13,http://en.wikipedia.org/wiki/2022_Hungarian_Gr...,Hungarian Grand Prix,"{'circuitId': 'hungaroring', 'url': 'http://en...",2022-07-31,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z
1093,1093,2022,14,http://en.wikipedia.org/wiki/2022_Belgian_Gran...,Belgian Grand Prix,"{'circuitId': 'spa', 'url': 'http://en.wikiped...",2022-08-28,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z
1094,1094,2022,15,http://en.wikipedia.org/wiki/2022_Dutch_Grand_...,Dutch Grand Prix,"{'circuitId': 'zandvoort', 'url': 'http://en.w...",2022-09-04,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z
1095,1095,2022,16,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'circuitId': 'monza', 'url': 'http://en.wikip...",2022-09-11,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z

In [689]:
driver_list = list(driver_df['driverRef'].unique())

In [690]:
point_history_dict = {i : 0 for i in driver_list}

In [691]:
df['Cumulative_Points'] = 0

for i in range(len(race_results_df)):
    
    res_dict = ast.literal_eval(race_results_df['Results'][i])
    
    for j in range(len(res_dict)):
        
        for k in range(len(df)):
        
            if (race_results_df['season'][i] == df['season'][k]) & (race_results_df['round'][i] == df['round'][k]) & (res_dict[j]['Driver']['driverId'] == df['driverRef'][k]):
                    
                if res_dict[j]['points'] == '':
                    res_dict[j]['points'] = 0
                
                df['Cumulative_Points'][k] = point_history_dict[res_dict[j]['Driver']['driverId']] + float(res_dict[j]['points'])    
                point_history_dict[res_dict[j]['Driver']['driverId']] += float(res_dict[j]['points'])

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2404537938.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cumulative_Points'][k] = point_history_dict[res_dict[j]['Driver']['driverId']] + float(res_dict[j]['points'])

In [692]:
driver_df

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
850,852,tsunoda,22,TSU,Yuki,Tsunoda,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda
851,853,mazepin,9,MAZ,Nikita,Mazepin,1999-03-02,Russian,http://en.wikipedia.org/wiki/Nikita_Mazepin
852,854,mick_schumacher,47,MSC,Mick,Schumacher,1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher
853,855,zhou,24,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou
854,856,de_vries,45,DEV,Nyck,de Vries,1995-02-06,Dutch,http://en.wikipedia.org/wiki/Nyck_de_Vries

In [693]:
df['yob'] = 0
for i in range(len(df)):
    
    for j in range(len(driver_df)):
        
        if df['driverRef'][i] == driver_df['driverRef'][j]:
            df['yob'][i] = int(driver_df['dob'][j][:4])

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2195991024.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['yob'][i] = int(driver_df['dob'][j][:4])

In [701]:
win_history_dict = {i : 0 for i in driver_list}

In [702]:
df['Cumulative_Wins'] = 0

for i in range(len(df)):
    
    if df['Driver_Position'][i] == 1:
        
        df['Cumulative_Wins'][i] = win_history_dict[df['driverRef'][i]] + 1
        win_history_dict[df['driverRef'][i]] += 1
    
    else:
        df['Cumulative_Wins'][i] = win_history_dict[df['driverRef'][i]]

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/1918225814.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cumulative_Wins'][i] = win_history_dict[df['driverRef'][i]] + 1
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/1918225814.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cumulative_Wins'][i] = win_history_dict[df['driverRef'][i]]

In [703]:
df.tail(40)

,circuitId,season,round,Driver_Position,Driver_Points,driverRef,constructorRef,grid_pos,completed_laps,race_status,Latitude,Longitude,raceId,weather,driverId,stop,Cumulative_Points,age_on_race,Cumulative_Wins
5325,villeneuve,2022,9,1.0,25.0,max_verstappen,red_bull,1.0,70.0,Finished,45.5000,-73.52280,1082,Sunny,830,Two,1628.5,25,26
5326,villeneuve,2022,9,2.0,19.0,sainz,ferrari,3.0,70.0,Finished,45.5000,-73.52280,1082,Sunny,832,Two,317.0,28,0
5327,villeneuve,2022,9,3.0,15.0,hamilton,mercedes,4.0,70.0,Finished,45.5000,-73.52280,1082,Sunny,1,Two,4110.5,37,103
5328,villeneuve,2022,9,4.0,12.0,russell,mercedes,8.0,70.0,Finished,45.5000,-73.52280,1082,Sunny,847,Two,120.0,24,0
5329,villeneuve,2022,9,5.0,10.0,leclerc,ferrari,19.0,70.0,Finished,45.5000,-73.52280,1082,Sunny,844,One,566.0,25,4
5330,silverstone,2022,10,1.0,25.0,sainz,ferrari,1.0,52.0,Finished,52.0786,-1.01694,1083,Cloudy,832,Three,342.0,28,1
5331,silverstone,2022,10,2.0,18.0,perez,red_bull,4.0,52.0,Finished,52.0786,-1.01694,1083,Cloudy,815,Three,634.0,32,3
5332,silverstone,2022,10,3.0,16.0,hamilton,mercedes,5.0,52.0,Finished,52.0786,-1.01694,1083,Cloudy,1,Three,4126.5,37,103
5333,silverstone,2022,10,4.0,12.0,leclerc,ferrari,3.0,52.0,Finished,52.0786,-1.01694,1083,Cloudy,844,Two,578.0,25,4
5334,silverstone,2022,10,5.0,10.0,alonso,alpine,7.0,52.0,Finished,52.0786,-1.01694,1083,Cloudy,4,Three,1691.0,41,32
5335,red_bull_ring,2022,11,1.0,25.0,leclerc,ferrari,2.0,71.0,Finished,47.2197,14.76470,1084,Cloudy,844,Three,603.0,25,5
5336,red_bull_ring,2022,11,2.0,19.0,max_verstappen,red_bull,1.0,71.0,Finished,47.2197,14.76470,1084,Cloudy,830,Three,1647.5,25,26
5337,red_bull_ring,2022,11,3.0,15.0,hamilton,mercedes,8.0,71.0,Finished,47.2197,14.76470,1084,Cloudy,1,Two,4141.5,37,103
5338,red_bull_ring,2022,11,4.0,12.0,russell,mercedes,4.0,71.0,Finished,47.2197,14.76470,1084,Cloudy,847,Two,132.0,24,0
5339,red_bull_ring,2022,11,5.0,10.0,ocon,alpine,6.0,71.0,Finished,47.2197,14.76470,1084,Cloudy,839,Two,105.0,26,1
5340,ricard,2022,12,1.0,25.0,max_verstappen,red_bull,2.0,53.0,Finished,43.2506,5.79167,1085,Sunny,830,One,1672.5,25,27
5341,ricard,2022,12,2.0,18.0,hamilton,mercedes,4.0,53.0,Finished,43.2506,5.79167,1085,Sunny,1,One,4159.5,37,103
5342,ricard,2022,12,3.0,15.0,russell,mercedes,6.0,53.0,Finished,43.2506,5.79167,1085,Sunny,847,One,147.0,24,0
5343,ricard,2022,12,4.0,12.0,perez,red_bull,3.0,53.0,Finished,43.2506,5.79167,1085,Sunny,815,One,646.0,32,3
5344,ricard,2022,12,5.0,11.0,sainz,ferrari,19.0,53.0,Finished,43.2506,5.79167,1085,Sunny,832,Two,353.0,28,1
5345,hungaroring,2022,13,1.0,25.0,max_verstappen,red_bull,10.0,70.0,Finished,47.5789,19.24860,1086,Rainy,830,Two,1697.5,25,28
5346,hungaroring,2022,13,2.0,19.0,hamilton,mercedes,7.0,70.0,Finished,47.5789,19.24860,1086,Rainy,1,Two,4178.5,37,103
5347,hungaroring,2022,13,3.0,15.0,russell,mercedes,1.0,70.0,Finished,47.5789,19.24860,1086,Rainy,847,Two,162.0,24,0
5348,hungaroring,2022,13,4.0,12.0,sainz,ferrari,2.0,70.0,Finished,47.5789,19.24860,1086,Rainy,832,Two,365.0,28,1
5349,hungaroring,2022,13,5.0,10.0,perez,red_bull,11.0,70.0,Finished,47.5789,19.24860,1086,Rainy,815,Two,656.0,32,3
5350,spa,2022,14,1.0,26.0,max_verstappen,red_bull,14.0,44.0,Finished,50.4372,5.97139,1087,Sunny,830,Two,1723.5,25,29
5351,spa,2022,14,2.0,18.0,perez,red_bull,2.0,44.0,Finished,50.4372,5.97139,1087,Sunny,815,Two,674.0,32,3
5352,spa,2022,14,3.0,15.0,sainz,ferrari,1.0,44.0,Finished,50.4372,5.97139,1087,Sunny,832,Two,380.0,28,1
5353,spa,2022,14,4.0,12.0,russell,mercedes,5.0,44.0,Finished,50.4372,5.97139,1087,Sunny,847,Two,174.0,24,0
5354,spa,2022,14,5.0,10.0,alonso,alpine,3.0,44.0,Finished,50.4372,5.97139,1087,Sunny,4,Two,1701.0,41,32
5355,zandvoort,2022,15,1.0,26.0,max_verstappen,red_bull,1.0,72.0,Finished,52.3888,4.54092,1088,Cloudy,830,Four,1749.5,25,30
5356,zandvoort,2022,15,2.0,18.0,russell,mercedes,6.0,72.0,Finished,52.3888,4.54092,1088,Cloudy,847,Three,192.0,24,0
5357,zandvoort,2022,15,3.0,15.0,leclerc,ferrari,2.0,72.0,Finished,52.3888,4.54092,1088,Cloudy,844,Four,618.0,25,5
5358,zandvoort,2022,15,4.0,12.0,hamilton,mercedes,4.0,72.0,Finished,52.3888,4.54092,1088,Cloudy,1,Three,4190.5,37,103
5359,zandvoort,2022,15,5.0,10.0,perez,red_bull,5.0,72.0,Finished,52.3888,4.54092,1088,Cloudy,815,Four,684.0,32,3
5360,monza,2022,16,1.0,25.0,max_verstappen,red_bull,7.0,53.0,Finished,45.6156,9.28111,1089,Sunny,830,Two,1774.5,25,31
5361,monza,2022,16,2.0,18.0,leclerc,ferrari,1.0,53.0,Finished,45.6156,9.28111,1089,Sunny,844,Three,636.0,25,5
5362,monza,2022,16,3.0,15.0,russell,mercedes,2.0,53.0,Finished,45.6156,9.28111,1089,Sunny,847,Two,207.0,24,0
5363,monza,2022,16,4.0,12.0,sainz,ferrari,18.0,53.0,Finished,45.6156,9.28111,1089,Sunny,832,Two,392.0,28,1
5364,monza,2022,16,5.0,10.0,hamilton,mercedes,19.0,53.0,Finished,45.6156,9.28111,1089,Sunny,1,One,4200.5,37,103

In [704]:
df

,circuitId,season,round,Driver_Position,Driver_Points,driverRef,constructorRef,grid_pos,completed_laps,race_status,Latitude,Longitude,raceId,weather,driverId,stop,Cumulative_Points,age_on_race,Cumulative_Wins
0,silverstone,1950,1,1.0,9.0,farina,alfa,1.0,70.0,Finished,52.0786,-1.01694,833,Fine,642,Not Available,9.0,44,1
1,silverstone,1950,1,2.0,6.0,fagioli,alfa,2.0,70.0,Finished,52.0786,-1.01694,833,Fine,786,Not Available,6.0,52,0
2,silverstone,1950,1,3.0,4.0,reg_parnell,alfa,4.0,70.0,Finished,52.0786,-1.01694,833,Fine,686,Not Available,4.0,39,0
3,silverstone,1950,1,4.0,3.0,cabantous,lago,6.0,68.0,Lapped,52.0786,-1.01694,833,Fine,704,Not Available,3.0,46,0
4,silverstone,1950,1,5.0,2.0,rosier,lago,9.0,68.0,Lapped,52.0786,-1.01694,833,Fine,627,Not Available,2.0,45,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5360,monza,2022,16,1.0,25.0,max_verstappen,red_bull,7.0,53.0,Finished,45.6156,9.28111,1089,Sunny,830,Two,1774.5,25,31
5361,monza,2022,16,2.0,18.0,leclerc,ferrari,1.0,53.0,Finished,45.6156,9.28111,1089,Sunny,844,Three,636.0,25,5
5362,monza,2022,16,3.0,15.0,russell,mercedes,2.0,53.0,Finished,45.6156,9.28111,1089,Sunny,847,Two,207.0,24,0
5363,monza,2022,16,4.0,12.0,sainz,ferrari,18.0,53.0,Finished,45.6156,9.28111,1089,Sunny,832,Two,392.0,28,1
5364,monza,2022,16,5.0,10.0,hamilton,mercedes,19.0,53.0,Finished,45.6156,9.28111,1089,Sunny,1,One,4200.5,37,103

In [710]:
ast.literal_eval(race_results_df['Results'][0])[0]['grid']

'1'

In [769]:
podium_per_race = {}

for i in range(len(race_results_df)):
    
    result = ast.literal_eval(race_results_df['Results'][i])
     
    for j in range(len(result)):
         
        if result[j]['grid'] == '1':
            
            driver = result[j]['Driver']['driverId']
             
            podium_per_race[str(race_results_df['season'][i]) + '_' + str(race_results_df['round'][i])] = driver

In [774]:
df['Podiums'] = ''

for i in range(len(df)):
    
    for keys in podium_per_race:
    
        if str(df['season'][i]) + '_' + str(df['round'][i]) == keys:
            
            df['Podiums'][i] = podium_per_race[keys]

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2605809172.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Podiums'][i] = podium_per_race[keys]

In [789]:
df1 = df.groupby(['season', 'round'], as_index = False)['Podiums'].max()

In [825]:
df1['counter'] = ''

for i in range(len(df1)):
    
    df1['counter'][i] = dict(Counter(df1['Podiums'][:i+1]))

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2661951960.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['counter'][i] = dict(Counter(df1['Podiums'][:i+1]))

In [827]:
df = pd.merge(df, df1, on = ['season', 'round'], how = 'left')

In [829]:
df.drop(['Podiums_y'], axis = 1, inplace=True)

In [831]:
df.rename(columns = {'Podiums_x' : 'Podiums'}, inplace=True)

In [835]:
df['podium_count'] = 0

for i in range(len(df)):
    
    if df['driverRef'][i] in df['counter'][i].keys():
        df['podium_count'][i] = df['counter'][i][df['driverRef'][i]]
    
    else:
        df['podium_count'][i] = 0

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3990981498.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['podium_count'][i] = df['counter'][i][df['driverRef'][i]]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3990981498.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['podium_count'][i] = 0

In [841]:
df.to_csv('../../data/01-modified-data/data_cleaned.csv', index=False)

## New Try

In [1091]:
season_info = df.groupby(['season', 'round'], as_index = False).count().iloc[:, :2]

In [1092]:
race_results_df['season_round'] = ''

for i in range(len(race_results_df)):
    
    race_results_df['season_round'][i] = str(race_results_df['season'][i]) + '_' + str(race_results_df['round'][i])

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/1772845875.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results_df['season_round'][i] = str(race_results_df['season'][i]) + '_' + str(race_results_df['round'][i])

In [1093]:
season_info['season_round'] = ''

for i in range(len(season_info)):
    
    season_info['season_round'][i] = str(season_info['season'][i]) + '_' + str(season_info['round'][i])

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2661518946.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_info['season_round'][i] = str(season_info['season'][i]) + '_' + str(season_info['round'][i])

In [1094]:
df1 = pd.merge(season_info, race_results_df, on = 'season_round', how = 'inner')

In [1095]:
df1.drop(['season_y', 'round_y', 'Unnamed: 0'], axis = 1, inplace=True)

In [1097]:
df1

,season_x,round_x,season_round,url,raceName,Circuit,date,Results,time
0,1950,1,1950_1,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,"{'circuitId': 'silverstone', 'url': 'http://en...",1950-05-13,"[{'number': '2', 'position': '1', 'positionTex...",NaN
1,1950,2,1950_2,http://en.wikipedia.org/wiki/1950_Monaco_Grand...,Monaco Grand Prix,"{'circuitId': 'monaco', 'url': 'http://en.wiki...",1950-05-21,"[{'number': '34', 'position': '1', 'positionTe...",NaN
2,1950,3,1950_3,http://en.wikipedia.org/wiki/1950_Indianapolis...,Indianapolis 500,"{'circuitId': 'indianapolis', 'url': 'http://e...",1950-05-30,"[{'number': '1', 'position': '1', 'positionTex...",NaN
3,1950,4,1950_4,http://en.wikipedia.org/wiki/1950_Swiss_Grand_...,Swiss Grand Prix,"{'circuitId': 'bremgarten', 'url': 'http://en....",1950-06-04,"[{'number': '16', 'position': '1', 'positionTe...",NaN
4,1950,5,1950_5,http://en.wikipedia.org/wiki/1950_Belgian_Gran...,Belgian Grand Prix,"{'circuitId': 'spa', 'url': 'http://en.wikiped...",1950-06-18,"[{'number': '10', 'position': '1', 'positionTe...",NaN
...,...,...,...,...,...,...,...,...,...
1091,2022,12,2022_12,http://en.wikipedia.org/wiki/2022_French_Grand...,French Grand Prix,"{'circuitId': 'ricard', 'url': 'http://en.wiki...",2022-07-24,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z
1092,2022,13,2022_13,http://en.wikipedia.org/wiki/2022_Hungarian_Gr...,Hungarian Grand Prix,"{'circuitId': 'hungaroring', 'url': 'http://en...",2022-07-31,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z
1093,2022,14,2022_14,http://en.wikipedia.org/wiki/2022_Belgian_Gran...,Belgian Grand Prix,"{'circuitId': 'spa', 'url': 'http://en.wikiped...",2022-08-28,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z
1094,2022,15,2022_15,http://en.wikipedia.org/wiki/2022_Dutch_Grand_...,Dutch Grand Prix,"{'circuitId': 'zandvoort', 'url': 'http://en.w...",2022-09-04,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z
1095,2022,16,2022_16,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'circuitId': 'monza', 'url': 'http://en.wikip...",2022-09-11,"[{'number': '1', 'position': '1', 'positionTex...",13:00:00Z

In [1098]:
main_df = pd.DataFrame()

for i in range(len(df1)):
    
    data1 = pd.DataFrame(ast.literal_eval(df1['Results'][i]))
    data1['season'] = df1['season_x'][i]
    data1['round'] = df1['round_x'][i]
    data1['season_round'] = df1['season_round'][i]
    data1['circuitId'] = ast.literal_eval(df1['Circuit'][i])['circuitId']
    data1['date'] = df1['date'][i]
    data1['url'] = df1['url'][i]
    data1['raceName	'] = df1['raceName'][i]
    
    main_df = pd.concat([main_df, data1], axis = 0)

In [1099]:
main_df.reset_index(inplace=True)

In [1100]:
main_df

,index,number,position,positionText,points,Driver,Constructor,grid,laps,status,Time,season,round,season_round,circuitId,date,url,raceName\t,FastestLap
0,0,2,1,1,9,"{'driverId': 'farina', 'url': 'http://en.wikip...","{'constructorId': 'alfa', 'url': 'http://en.wi...",1,70,Finished,"{'millis': '8003600', 'time': '2:13:23.6'}",1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN
1,1,3,2,2,6,"{'driverId': 'fagioli', 'url': 'http://en.wiki...","{'constructorId': 'alfa', 'url': 'http://en.wi...",2,70,Finished,"{'millis': '8006200', 'time': '+2.6'}",1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN
2,2,4,3,3,4,"{'driverId': 'reg_parnell', 'url': 'http://en....","{'constructorId': 'alfa', 'url': 'http://en.wi...",4,70,Finished,"{'millis': '8055600', 'time': '+52.0'}",1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN
3,3,14,4,4,3,"{'driverId': 'cabantous', 'url': 'http://en.wi...","{'constructorId': 'lago', 'url': 'http://en.wi...",6,68,+2 Laps,NaN,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN
4,4,15,5,5,2,"{'driverId': 'rosier', 'url': 'http://en.wikip...","{'constructorId': 'lago', 'url': 'http://en.wi...",9,68,+2 Laps,NaN,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,15,20,16,16,0,"{'driverId': 'kevin_magnussen', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",16,52,+1 Lap,NaN,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '16', 'lap': '37', 'Time': {'time': '..."
25716,16,3,17,R,0,"{'driverId': 'ricciardo', 'permanentNumber': '...","{'constructorId': 'mclaren', 'url': 'http://en...",4,45,Oil leak,NaN,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '12', 'lap': '39', 'Time': {'time': '..."
25717,17,18,18,R,0,"{'driverId': 'stroll', 'permanentNumber': '18'...","{'constructorId': 'aston_martin', 'url': 'http...",12,39,Engine,NaN,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '19', 'lap': '34', 'Time': {'time': '..."
25718,18,14,19,R,0,"{'driverId': 'alonso', 'permanentNumber': '14'...","{'constructorId': 'alpine', 'url': 'http://en....",6,31,Water pressure,NaN,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '18', 'lap': '7', 'Time': {'time': '1..."
25719,19,5,20,R,0,"{'driverId': 'vettel', 'permanentNumber': '5',...","{'constructorId': 'aston_martin', 'url': 'http...",11,10,Engine,NaN,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '20', 'lap': '4', 'Time': {'time': '1..."

In [1101]:
main_df['driverRef'] = ''
main_df['yob'] = 0
main_df['constructorRef'] = ''

for i in range(len(main_df)):
    
    main_df['driverRef'][i] = main_df['Driver'][i]['driverId']
    main_df['yob'][i] = int(main_df['Driver'][i]['dateOfBirth'][:4])
    main_df['constructorRef'][i] = main_df['Constructor'][i]['constructorId']

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3578735019.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['driverRef'][i] = main_df['Driver'][i]['driverId']
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3578735019.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['yob'][i] = int(main_df['Driver'][i]['dateOfBirth'][:4])
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3578735019.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['constructorRef'][i] = main_df['Constructor'][i]['constructorId']

In [1102]:
main_df.drop(['Driver', 'Constructor', 'index', 'number', 'positionText', 'Time'], axis = 1, inplace=True)

In [1103]:
main_df

,position,points,grid,laps,status,season,round,season_round,circuitId,date,url,raceName\t,FastestLap,driverRef,yob,constructorRef
0,1,9,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,farina,1906,alfa
1,2,6,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,fagioli,1898,alfa
2,3,4,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,reg_parnell,1911,alfa
3,4,3,6,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,cabantous,1904,lago
4,5,2,9,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,rosier,1905,lago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,16,0,16,52,+1 Lap,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '16', 'lap': '37', 'Time': {'time': '...",kevin_magnussen,1992,haas
25716,17,0,4,45,Oil leak,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '12', 'lap': '39', 'Time': {'time': '...",ricciardo,1989,mclaren
25717,18,0,12,39,Engine,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '19', 'lap': '34', 'Time': {'time': '...",stroll,1998,aston_martin
25718,19,0,6,31,Water pressure,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '18', 'lap': '7', 'Time': {'time': '1...",alonso,1981,alpine
25719,20,0,11,10,Engine,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '20', 'lap': '4', 'Time': {'time': '1...",vettel,1987,aston_martin

In [1104]:
def get_infobox(url):
    response = requests.get(url)
    bs = BeautifulSoup(response.text)

    table = bs.find('table', {'class' :'infobox vevent'})
    result = {}
    row_count = 0
    if table is None:
        pass
    else:
        for tr in table.find_all('tr'):
            if tr.find('th'):
                key = tr.find('th').text.strip()
                if tr.find('td'):
                    value = tr.find('td').text.strip()
                    result[key] = value
                else:
                    result[key] = ''
            else:
                pass
    return result

In [1105]:
url_df = main_df.groupby(['season_round'], as_index = False)['url'].max()

In [1106]:
url_df['weather'] = np.nan

for i in range(0, len(url_df)):
    infobox = get_infobox(url_df['url'][i])
    infobox_keys = get_infobox(url_df['url'][i]).keys()
    
    if 'Weather' in infobox_keys:
        url_df['weather'][i] = infobox['Weather']
    else:
        url_df['weather'][i] = np.nan

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3666777405.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  url_df['weather'][i] = infobox['Weather']

In [1107]:
main_df = pd.merge(main_df, url_df, on = 'season_round', how = 'left')

In [1108]:
main_df

,position,points,grid,laps,status,season,round,season_round,circuitId,date,url_x,raceName\t,FastestLap,driverRef,yob,constructorRef,url_y,weather
0,1,9,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,farina,1906,alfa,http://en.wikipedia.org/wiki/1950_British_Gran...,"Sunny, mild, dry."
1,2,6,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,fagioli,1898,alfa,http://en.wikipedia.org/wiki/1950_British_Gran...,"Sunny, mild, dry."
2,3,4,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,reg_parnell,1911,alfa,http://en.wikipedia.org/wiki/1950_British_Gran...,"Sunny, mild, dry."
3,4,3,6,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,cabantous,1904,lago,http://en.wikipedia.org/wiki/1950_British_Gran...,"Sunny, mild, dry."
4,5,2,9,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,British Grand Prix,NaN,rosier,1905,lago,http://en.wikipedia.org/wiki/1950_British_Gran...,"Sunny, mild, dry."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,16,0,16,52,+1 Lap,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '16', 'lap': '37', 'Time': {'time': '...",kevin_magnussen,1992,haas,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Sunny
25716,17,0,4,45,Oil leak,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '12', 'lap': '39', 'Time': {'time': '...",ricciardo,1989,mclaren,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Sunny
25717,18,0,12,39,Engine,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '19', 'lap': '34', 'Time': {'time': '...",stroll,1998,aston_martin,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Sunny
25718,19,0,6,31,Water pressure,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '18', 'lap': '7', 'Time': {'time': '1...",alonso,1981,alpine,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Sunny
25719,20,0,11,10,Engine,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Italian Grand Prix,"{'rank': '20', 'lap': '4', 'Time': {'time': '1...",vettel,1987,aston_martin,http://en.wikipedia.org/wiki/2022_Italian_Gran...,Sunny

In [1109]:
for i in range(len(main_df)):
    
    if main_df['weather'][i] is not NaN:
        
        if ('rain' in main_df['weather'][i].lower()) | ('wet' in main_df['weather'][i].lower()) | ('showers' in main_df['weather'][i].lower()) | ('drizzle' in main_df['weather'][i].lower()) | ('rainy' in main_df['weather'][i].lower()) | ('drizzly' in main_df['weather'][i].lower()):
            main_df['weather'][i] = 'Rainy'
        
        elif ('snow' in main_df['weather'][i].lower()) | ('cold' in main_df['weather'][i].lower()) | ('frost' in main_df['weather'][i].lower()) | ('icy' in main_df['weather'][i].lower()):
            main_df['weather'][i] = 'Snowy'
        
        elif ('windy' in main_df['weather'][i].lower()) | ('wind' in main_df['weather'][i].lower()) | ('gusty' in main_df['weather'][i].lower()) | ('blustery' in main_df['weather'][i].lower()):
            main_df['weather'][i] = 'Windy'
        
        elif ('cloudy' in main_df['weather'][i].lower()) | ('overcast' in main_df['weather'][i].lower()) | ('partly cloudy' in main_df['weather'][i].lower()) | ('partly sunny' in main_df['weather'][i].lower()) | ('hazy' in main_df['weather'][i].lower()) | ('foggy' in main_df['weather'][i].lower()) | ('fog' in main_df['weather'][i].lower()) | ('misty' in main_df['weather'][i].lower()) | ('mist' in main_df['weather'][i].lower()) | ('cloud' in main_df['weather'][i].lower()):
            main_df['weather'][i] = 'Cloudy'
            
        elif ('fine' in main_df['weather'][i].lower()) | ('fair' in main_df['weather'][i].lower()) | ('mild' in main_df['weather'][i].lower()):
            main_df['weather'][i] = 'Fine'
        
        elif ('sunny' in main_df['weather'][i].lower()) | ('clear' in main_df['weather'][i].lower()) | ('warm' in main_df['weather'][i].lower()) | ('hot' in main_df['weather'][i].lower()) | ('dry' in main_df['weather'][i].lower()):
            main_df['weather'][i] = 'Sunny'
            
        else:
            main_df['weather'][i] = 'Sunny'
    
    else:
        pass

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3493824297.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['weather'][i] = 'Fine'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3493824297.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['weather'][i] = 'Rainy'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3493824297.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['weather'][i] = 'Sunny'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3493824297.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['weather'][i] = 'Cloudy'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3493824297.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['weather'][i] = 'Windy'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3493824297.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['weather'][i] = 'Snowy'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/3493824297.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['weather'][i] = 'Sunny'

In [1110]:
main_df['weather'].value_counts()

Sunny     11611
Cloudy     3798
Rainy      3636
Windy      2493
Fine       1287
Snowy       159
Name: weather, dtype: int64

In [1112]:
main_df.drop(['url_y', 'raceName\t', 'FastestLap'], axis = 1, inplace=True)

In [1113]:
main_df

,position,points,grid,laps,status,season,round,season_round,circuitId,date,url_x,driverRef,yob,constructorRef,weather
0,1,9,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,farina,1906,alfa,Fine
1,2,6,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,fagioli,1898,alfa,Fine
2,3,4,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,reg_parnell,1911,alfa,Fine
3,4,3,6,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,cabantous,1904,lago,Fine
4,5,2,9,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,http://en.wikipedia.org/wiki/1950_British_Gran...,rosier,1905,lago,Fine
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,16,0,16,52,+1 Lap,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,kevin_magnussen,1992,haas,Sunny
25716,17,0,4,45,Oil leak,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,ricciardo,1989,mclaren,Sunny
25717,18,0,12,39,Engine,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,stroll,1998,aston_martin,Sunny
25718,19,0,6,31,Water pressure,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,alonso,1981,alpine,Sunny
25719,20,0,11,10,Engine,2022,16,2022_16,monza,2022-09-11,http://en.wikipedia.org/wiki/2022_Italian_Gran...,vettel,1987,aston_martin,Sunny

In [1114]:
pitstop_df = pd.read_csv('../../data/00-raw-data/pit_stops.csv')
pitstop_count = pitstop_df.groupby(['raceId', 'driverId'], as_index=False)['stop'].count()

In [1115]:
race_df = pd.read_csv('../../data/00-raw-data/races.csv')
race_df.rename(columns={'year':'season'}, inplace=True)
race_df =  race_df[['raceId', 'season', 'round', 'circuitId']]
race_df.head()

   raceId  season  round  circuitId
0       1    2009      1          1
1       2    2009      2          2
2       3    2009      3         17
3       4    2009      4          3
4       5    2009      5          4

In [1116]:
driver_df = pd.read_csv('../../data/00-raw-data/drivers.csv')
driver_df.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [1117]:
pitstop_count

      raceId  driverId  stop
0        841         1     2
1        841         2     2
2        841         3     1
3        841         4     3
4        841         5     1
...      ...       ...   ...
4586    1089       849     2
4587    1089       852     2
4588    1089       854     1
4589    1089       855     1
4590    1089       856     1

[4591 rows x 3 columns]

In [1118]:
main_df = pd.merge(main_df, driver_df, on = ['driverRef'], how = 'left')

In [1119]:
main_df.drop(['url_x', 'driverRef', 'code', 'number', 'nationality', 'forename', 'surname', 'dob'], axis = 1, inplace=True)

In [1120]:
main_df = pd.merge(main_df, race_df, on = ['season', 'round'], how = 'left')

In [1121]:
main_df.rename(columns={'circuitId_x' : 'circuitRef', 'circuitId_y' : 'circuitId'}, inplace=True)
main_df

,position,points,grid,laps,status,season,round,season_round,circuitRef,date,yob,constructorRef,weather,driverId,url,raceId,circuitId
0,1,9,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1906,alfa,Fine,642,http://en.wikipedia.org/wiki/Nino_Farina,833,9
1,2,6,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1898,alfa,Fine,786,http://en.wikipedia.org/wiki/Luigi_Fagioli,833,9
2,3,4,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1911,alfa,Fine,686,http://en.wikipedia.org/wiki/Reg_Parnell,833,9
3,4,3,6,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,1904,lago,Fine,704,http://en.wikipedia.org/wiki/Yves_Giraud_Caban...,833,9
4,5,2,9,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,1905,lago,Fine,627,http://en.wikipedia.org/wiki/Louis_Rosier,833,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,16,0,16,52,+1 Lap,2022,16,2022_16,monza,2022-09-11,1992,haas,Sunny,825,http://en.wikipedia.org/wiki/Kevin_Magnussen,1089,14
25716,17,0,4,45,Oil leak,2022,16,2022_16,monza,2022-09-11,1989,mclaren,Sunny,817,http://en.wikipedia.org/wiki/Daniel_Ricciardo,1089,14
25717,18,0,12,39,Engine,2022,16,2022_16,monza,2022-09-11,1998,aston_martin,Sunny,840,http://en.wikipedia.org/wiki/Lance_Stroll,1089,14
25718,19,0,6,31,Water pressure,2022,16,2022_16,monza,2022-09-11,1981,alpine,Sunny,4,http://en.wikipedia.org/wiki/Fernando_Alonso,1089,14
25719,20,0,11,10,Engine,2022,16,2022_16,monza,2022-09-11,1987,aston_martin,Sunny,20,http://en.wikipedia.org/wiki/Sebastian_Vettel,1089,14

In [1122]:
main_df = pd.merge(main_df, pitstop_count, on = ['raceId', 'driverId'], how = 'left')

In [1123]:
main_df

,position,points,grid,laps,status,season,round,season_round,circuitRef,date,yob,constructorRef,weather,driverId,url,raceId,circuitId,stop
0,1,9,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1906,alfa,Fine,642,http://en.wikipedia.org/wiki/Nino_Farina,833,9,NaN
1,2,6,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1898,alfa,Fine,786,http://en.wikipedia.org/wiki/Luigi_Fagioli,833,9,NaN
2,3,4,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1911,alfa,Fine,686,http://en.wikipedia.org/wiki/Reg_Parnell,833,9,NaN
3,4,3,6,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,1904,lago,Fine,704,http://en.wikipedia.org/wiki/Yves_Giraud_Caban...,833,9,NaN
4,5,2,9,68,+2 Laps,1950,1,1950_1,silverstone,1950-05-13,1905,lago,Fine,627,http://en.wikipedia.org/wiki/Louis_Rosier,833,9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,16,0,16,52,+1 Lap,2022,16,2022_16,monza,2022-09-11,1992,haas,Sunny,825,http://en.wikipedia.org/wiki/Kevin_Magnussen,1089,14,2.0
25716,17,0,4,45,Oil leak,2022,16,2022_16,monza,2022-09-11,1989,mclaren,Sunny,817,http://en.wikipedia.org/wiki/Daniel_Ricciardo,1089,14,1.0
25717,18,0,12,39,Engine,2022,16,2022_16,monza,2022-09-11,1998,aston_martin,Sunny,840,http://en.wikipedia.org/wiki/Lance_Stroll,1089,14,1.0
25718,19,0,6,31,Water pressure,2022,16,2022_16,monza,2022-09-11,1981,alpine,Sunny,4,http://en.wikipedia.org/wiki/Fernando_Alonso,1089,14,NaN
25719,20,0,11,10,Engine,2022,16,2022_16,monza,2022-09-11,1987,aston_martin,Sunny,20,http://en.wikipedia.org/wiki/Sebastian_Vettel,1089,14,NaN

In [1124]:
for i in range(len(main_df)):
    
    if ('Lap' in main_df['status'][i]) | ('lap' in main_df['status'][i]):
        main_df['status'][i] = 'Lapped'
    
    elif 'Accident' in main_df['status'][i]:
        main_df['status'][i] = 'Accident'
        
    elif 'Finished' in main_df['status'][i]:
        main_df['status'][i] = 'Finished'
        
    else:
        main_df['status'][i] = 'Mechanical_Issue'

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2958011310.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['status'][i] = 'Finished'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2958011310.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['status'][i] = 'Lapped'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2958011310.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['status'][i] = 'Mechanical_Issue'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2958011310.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['status'][i] = 'Accident'

In [1125]:
main_df

,position,points,grid,laps,status,season,round,season_round,circuitRef,date,yob,constructorRef,weather,driverId,url,raceId,circuitId,stop
0,1,9,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1906,alfa,Fine,642,http://en.wikipedia.org/wiki/Nino_Farina,833,9,NaN
1,2,6,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1898,alfa,Fine,786,http://en.wikipedia.org/wiki/Luigi_Fagioli,833,9,NaN
2,3,4,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,1911,alfa,Fine,686,http://en.wikipedia.org/wiki/Reg_Parnell,833,9,NaN
3,4,3,6,68,Lapped,1950,1,1950_1,silverstone,1950-05-13,1904,lago,Fine,704,http://en.wikipedia.org/wiki/Yves_Giraud_Caban...,833,9,NaN
4,5,2,9,68,Lapped,1950,1,1950_1,silverstone,1950-05-13,1905,lago,Fine,627,http://en.wikipedia.org/wiki/Louis_Rosier,833,9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,16,0,16,52,Lapped,2022,16,2022_16,monza,2022-09-11,1992,haas,Sunny,825,http://en.wikipedia.org/wiki/Kevin_Magnussen,1089,14,2.0
25716,17,0,4,45,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,1989,mclaren,Sunny,817,http://en.wikipedia.org/wiki/Daniel_Ricciardo,1089,14,1.0
25717,18,0,12,39,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,1998,aston_martin,Sunny,840,http://en.wikipedia.org/wiki/Lance_Stroll,1089,14,1.0
25718,19,0,6,31,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,1981,alpine,Sunny,4,http://en.wikipedia.org/wiki/Fernando_Alonso,1089,14,NaN
25719,20,0,11,10,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,1987,aston_martin,Sunny,20,http://en.wikipedia.org/wiki/Sebastian_Vettel,1089,14,NaN

In [1126]:
main_df['age_on_race'] = main_df['season'] - main_df['yob']
main_df.drop('yob', axis = 1, inplace=True)

In [1127]:
main_df['stop'].fillna('Not Available', inplace=True)
main_df['weather'].fillna('Not Available', inplace=True)

In [1128]:
for i in range(len(main_df)):
    
    if main_df['stop'][i] == 1.0:
        main_df['stop'][i] = 'One'
    
    elif main_df['stop'][i] == 2.0:
        main_df['stop'][i] = 'Two'
    
    elif main_df['stop'][i] == 3.0:
        main_df['stop'][i] = 'Three'
    
    elif main_df['stop'][i] == 4.0:
        main_df['stop'][i] = 'Four'
    
    elif main_df['stop'][i] == 5.0:
        main_df['stop'][i] = 'Five'
    
    elif main_df['stop'][i] == 6.0:
        main_df['stop'][i] = 'Six'
        
    elif main_df['stop'][i] == 7.0:
        main_df['stop'][i] = 'Seven'
        
    else:
        pass

In [1129]:
main_df

,position,points,grid,laps,status,season,round,season_round,circuitRef,date,constructorRef,weather,driverId,url,raceId,circuitId,stop,age_on_race
0,1,9,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,alfa,Fine,642,http://en.wikipedia.org/wiki/Nino_Farina,833,9,Not Available,44
1,2,6,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,alfa,Fine,786,http://en.wikipedia.org/wiki/Luigi_Fagioli,833,9,Not Available,52
2,3,4,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,alfa,Fine,686,http://en.wikipedia.org/wiki/Reg_Parnell,833,9,Not Available,39
3,4,3,6,68,Lapped,1950,1,1950_1,silverstone,1950-05-13,lago,Fine,704,http://en.wikipedia.org/wiki/Yves_Giraud_Caban...,833,9,Not Available,46
4,5,2,9,68,Lapped,1950,1,1950_1,silverstone,1950-05-13,lago,Fine,627,http://en.wikipedia.org/wiki/Louis_Rosier,833,9,Not Available,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,16,0,16,52,Lapped,2022,16,2022_16,monza,2022-09-11,haas,Sunny,825,http://en.wikipedia.org/wiki/Kevin_Magnussen,1089,14,Two,30
25716,17,0,4,45,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,mclaren,Sunny,817,http://en.wikipedia.org/wiki/Daniel_Ricciardo,1089,14,One,33
25717,18,0,12,39,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,aston_martin,Sunny,840,http://en.wikipedia.org/wiki/Lance_Stroll,1089,14,One,24
25718,19,0,6,31,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,alpine,Sunny,4,http://en.wikipedia.org/wiki/Fernando_Alonso,1089,14,Not Available,41
25719,20,0,11,10,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,aston_martin,Sunny,20,http://en.wikipedia.org/wiki/Sebastian_Vettel,1089,14,Not Available,35

In [1130]:
main_df[['position', 'points', 'grid', 'laps', 'season', 'round', 'driverId', 'raceId', 'circuitId', 'age_on_race']] = main_df[['position', 'points', 'grid', 'laps', 'season', 'round', 'driverId', 'raceId', 'circuitId', 'age_on_race']].apply(pd.to_numeric)

In [1131]:
main_df['cumulative_points'] = main_df.groupby(['driverId'])['points'].cumsum()
main_df['cumulative_laps'] = main_df.groupby(['driverId'])['laps'].cumsum()

In [1132]:
main_df

,position,points,grid,laps,status,season,round,season_round,circuitRef,date,constructorRef,weather,driverId,url,raceId,circuitId,stop,age_on_race,cumulative_points,cumulative_laps
0,1,9.0,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,alfa,Fine,642,http://en.wikipedia.org/wiki/Nino_Farina,833,9,Not Available,44,9.0,70
1,2,6.0,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,alfa,Fine,786,http://en.wikipedia.org/wiki/Luigi_Fagioli,833,9,Not Available,52,6.0,70
2,3,4.0,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,alfa,Fine,686,http://en.wikipedia.org/wiki/Reg_Parnell,833,9,Not Available,39,4.0,70
3,4,3.0,6,68,Lapped,1950,1,1950_1,silverstone,1950-05-13,lago,Fine,704,http://en.wikipedia.org/wiki/Yves_Giraud_Caban...,833,9,Not Available,46,3.0,68
4,5,2.0,9,68,Lapped,1950,1,1950_1,silverstone,1950-05-13,lago,Fine,627,http://en.wikipedia.org/wiki/Louis_Rosier,833,9,Not Available,45,2.0,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25715,16,0.0,16,52,Lapped,2022,16,2022_16,monza,2022-09-11,haas,Sunny,825,http://en.wikipedia.org/wiki/Kevin_Magnussen,1089,14,Two,30,177.0,7226
25716,17,0.0,4,45,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,mclaren,Sunny,817,http://en.wikipedia.org/wiki/Daniel_Ricciardo,1089,14,One,33,1289.0,12445
25717,18,0.0,12,39,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,aston_martin,Sunny,840,http://en.wikipedia.org/wiki/Lance_Stroll,1089,14,One,24,181.0,6299
25718,19,0.0,6,31,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,alpine,Sunny,4,http://en.wikipedia.org/wiki/Fernando_Alonso,1089,14,Not Available,41,2039.0,18888
25719,20,0.0,11,10,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,aston_martin,Sunny,20,http://en.wikipedia.org/wiki/Sebastian_Vettel,1089,14,Not Available,35,3081.0,16084

In [1133]:
grid_df = main_df[['season', 'round', 'driverId']][main_df['grid'] == 1]

In [1134]:
main_df = pd.merge(main_df, grid_df, on = ['season', 'round'], how = 'left')
main_df.rename(columns={'driverId_x' : 'driverId', 'driverId_y' : 'pole_driverId'}, inplace=True)

In [1135]:
history_dict = {i : 0 for i in list(main_df['driverId'].unique())}

In [1136]:
main_df['pole_history'] = 0
    
for j in range(len(main_df)):
        
    if (main_df['driverId'][j] == main_df['pole_driverId'][j]):
            
        history_dict[main_df['driverId'][j]] += 1
        main_df['pole_history'][j] = history_dict[main_df['driverId'][j]]
        
    else:
        main_df['pole_history'][j] = history_dict[main_df['driverId'][j]]

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/4153785418.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['pole_history'][j] = history_dict[main_df['driverId'][j]]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/4153785418.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['pole_history'][j] = history_dict[main_df['driverId'][j]]

In [1137]:
win_df = main_df[['season_round', 'driverId']][main_df['position'] == 1]

In [1138]:
main_df = pd.merge(main_df, win_df, on = ['season_round'], how = 'left')

In [1139]:
main_df.rename(columns={'driverId_x' : 'driverId', 'driverId_y' : 'win_driverId'}, inplace=True)

In [1140]:
main_df

,position,points,grid,laps,status,season,round,season_round,circuitRef,date,...,url,raceId,circuitId,stop,age_on_race,cumulative_points,cumulative_laps,pole_driverId,pole_history,win_driverId
0,1,9.0,1,70,Finished,1950,1,1950_1,silverstone,1950-05-13,...,http://en.wikipedia.org/wiki/Nino_Farina,833,9,Not Available,44,9.0,70,642,1,642
1,2,6.0,2,70,Finished,1950,1,1950_1,silverstone,1950-05-13,...,http://en.wikipedia.org/wiki/Luigi_Fagioli,833,9,Not Available,52,6.0,70,642,0,642
2,3,4.0,4,70,Finished,1950,1,1950_1,silverstone,1950-05-13,...,http://en.wikipedia.org/wiki/Reg_Parnell,833,9,Not Available,39,4.0,70,642,0,642
3,4,3.0,6,68,Lapped,1950,1,1950_1,silverstone,1950-05-13,...,http://en.wikipedia.org/wiki/Yves_Giraud_Caban...,833,9,Not Available,46,3.0,68,642,0,642
4,5,2.0,9,68,Lapped,1950,1,1950_1,silverstone,1950-05-13,...,http://en.wikipedia.org/wiki/Louis_Rosier,833,9,Not Available,45,2.0,68,642,0,642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26936,16,0.0,16,52,Lapped,2022,16,2022_16,monza,2022-09-11,...,http://en.wikipedia.org/wiki/Kevin_Magnussen,1089,14,Two,30,177.0,7226,844,0,830
26937,17,0.0,4,45,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,...,http://en.wikipedia.org/wiki/Daniel_Ricciardo,1089,14,One,33,1289.0,12445,844,3,830
26938,18,0.0,12,39,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,...,http://en.wikipedia.org/wiki/Lance_Stroll,1089,14,One,24,181.0,6299,844,1,830
26939,19,0.0,6,31,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,...,http://en.wikipedia.org/wiki/Fernando_Alonso,1089,14,Not Available,41,2039.0,18888,844,22,830
26940,20,0.0,11,10,Mechanical_Issue,2022,16,2022_16,monza,2022-09-11,...,http://en.wikipedia.org/wiki/Sebastian_Vettel,1089,14,Not Available,35,3081.0,16084,844,57,830

In [1141]:
history_dict = {i : 0 for i in list(main_df['driverId'].unique())} 

main_df['win_history'] = 0
    
    
for j in range(len(main_df)):
        
    if (main_df['driverId'][j] == main_df['win_driverId'][j]):
            
        history_dict[main_df['driverId'][j]] += 1
        main_df['win_history'][j] = history_dict[main_df['driverId'][j]]
        
    else:
        main_df['win_history'][j] = history_dict[main_df['driverId'][j]]

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/579238326.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['win_history'][j] = history_dict[main_df['driverId'][j]]
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/579238326.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['win_history'][j] = history_dict[main_df['driverId'][j]]

In [1142]:
main_df.drop(['circuitRef', 'url', 'date'], axis = 1, inplace=True)

In [1143]:
main_df.columns

Index(['position', 'points', 'grid', 'laps', 'status', 'season', 'round',
       'season_round', 'constructorRef', 'weather', 'driverId', 'raceId',
       'circuitId', 'stop', 'age_on_race', 'cumulative_points',
       'cumulative_laps', 'pole_driverId', 'pole_history', 'win_driverId',
       'win_history'],
      dtype='object')

In [1144]:
main_df = main_df[['season', 'round', 'season_round', 'driverId', 'raceId',
                    'circuitId', 'position', 'points', 'grid', 'laps', 'status',
                    'constructorRef', 'weather', 'stop', 'age_on_race', 'cumulative_points',
                    'cumulative_laps', 'pole_driverId', 'pole_history', 'win_driverId',
                    'win_history']]

In [1145]:
main_df

,season,round,season_round,driverId,raceId,circuitId,position,points,grid,laps,...,constructorRef,weather,stop,age_on_race,cumulative_points,cumulative_laps,pole_driverId,pole_history,win_driverId,win_history
0,1950,1,1950_1,642,833,9,1,9.0,1,70,...,alfa,Fine,Not Available,44,9.0,70,642,1,642,1
1,1950,1,1950_1,786,833,9,2,6.0,2,70,...,alfa,Fine,Not Available,52,6.0,70,642,0,642,0
2,1950,1,1950_1,686,833,9,3,4.0,4,70,...,alfa,Fine,Not Available,39,4.0,70,642,0,642,0
3,1950,1,1950_1,704,833,9,4,3.0,6,68,...,lago,Fine,Not Available,46,3.0,68,642,0,642,0
4,1950,1,1950_1,627,833,9,5,2.0,9,68,...,lago,Fine,Not Available,45,2.0,68,642,0,642,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26936,2022,16,2022_16,825,1089,14,16,0.0,16,52,...,haas,Sunny,Two,30,177.0,7226,844,0,830,0
26937,2022,16,2022_16,817,1089,14,17,0.0,4,45,...,mclaren,Sunny,One,33,1289.0,12445,844,3,830,8
26938,2022,16,2022_16,840,1089,14,18,0.0,12,39,...,aston_martin,Sunny,One,24,181.0,6299,844,1,830,0
26939,2022,16,2022_16,4,1089,14,19,0.0,6,31,...,alpine,Sunny,Not Available,41,2039.0,18888,844,22,830,32
26940,2022,16,2022_16,20,1089,14,20,0.0,11,10,...,aston_martin,Sunny,Not Available,35,3081.0,16084,844,57,830,53

In [1146]:
main_df['label'] = ''

for i in range(len(main_df)):
    
    if main_df['position'][i] in [1, 2, 3]:
        main_df['label'][i] = 'Podium'
        
    elif main_df['position'][i] in [4, 5, 6, 7, 8, 9, 10]:
        main_df['label'][i] = 'Top_10'
    
    else:
        main_df['label'][i] = 'Outside_Top_10'

/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2080856308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['label'] = ''
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2080856308.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['label'][i] = 'Podium'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2080856308.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['label'][i] = 'Top_10'
/var/folders/80/kkd433150p52z36v9dx3c_p00000gn/T/ipykernel_14535/2080856308.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['label'][i] = 'Outside_Top_10'

In [1147]:
main_df

,season,round,season_round,driverId,raceId,circuitId,position,points,grid,laps,...,weather,stop,age_on_race,cumulative_points,cumulative_laps,pole_driverId,pole_history,win_driverId,win_history,label
0,1950,1,1950_1,642,833,9,1,9.0,1,70,...,Fine,Not Available,44,9.0,70,642,1,642,1,Podium
1,1950,1,1950_1,786,833,9,2,6.0,2,70,...,Fine,Not Available,52,6.0,70,642,0,642,0,Podium
2,1950,1,1950_1,686,833,9,3,4.0,4,70,...,Fine,Not Available,39,4.0,70,642,0,642,0,Podium
3,1950,1,1950_1,704,833,9,4,3.0,6,68,...,Fine,Not Available,46,3.0,68,642,0,642,0,Top_10
4,1950,1,1950_1,627,833,9,5,2.0,9,68,...,Fine,Not Available,45,2.0,68,642,0,642,0,Top_10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26936,2022,16,2022_16,825,1089,14,16,0.0,16,52,...,Sunny,Two,30,177.0,7226,844,0,830,0,Outside_Top_10
26937,2022,16,2022_16,817,1089,14,17,0.0,4,45,...,Sunny,One,33,1289.0,12445,844,3,830,8,Outside_Top_10
26938,2022,16,2022_16,840,1089,14,18,0.0,12,39,...,Sunny,One,24,181.0,6299,844,1,830,0,Outside_Top_10
26939,2022,16,2022_16,4,1089,14,19,0.0,6,31,...,Sunny,Not Available,41,2039.0,18888,844,22,830,32,Outside_Top_10
26940,2022,16,2022_16,20,1089,14,20,0.0,11,10,...,Sunny,Not Available,35,3081.0,16084,844,57,830,53,Outside_Top_10

In [1150]:
main_df.to_csv('../../data/01-modified-data/data_cleaned.csv', index=False)